Initial commit
che-dockerfiles/che-sidecar-scala pull request #1
Opened 2020-04-26 18:51 UTC by sideeffffect

2020-04-26 19:03 UTC, sideeffffect commented
This creates a side-car image for Scala as per https://github.com/eclipse/che-plugin-registry/pull/356#issuecomment-606226761

Please have a look that I'm doing the right thing, both from the point of view of Metals (@olafurpg, @tgodzik) and Che (@amisevsk, @ericwill)

The only possible complication here is that the version of the extension is `1.8.6` and I don't have the permissions to create branches in this repo, so I target the branch `1.7.7` which was already pre-created for me.

(sorry it took so long, I was a busier than I thought)

2020-04-29 20:31 UTC, ericwill requested changes
We need an entrypoint into the container, i.e. `entrypoint.sh` and all that comes with it. Take a look at the `Dockerfile` and `etc` directory in: https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling/tree/1.1.0

2020-04-29 20:31 UTC, ericwill commented on .github/workflows/build-publish.yaml
> +# Copyright (c) 2019 Red Hat, Inc.
Year needs to be updated.

2020-04-29 20:31 UTC, ericwill commented on .github/workflows/pr-check.yaml
> +# Copyright (c) 2019 Red Hat, Inc.
Year needs to be adjusted.

2020-04-29 20:31 UTC, ericwill commented on Dockerfile
> +RUN curl -Ls https://raw.githubusercontent.com/coursier/coursier/gh-pages/coursier > /usr/local/bin/coursier && \
These two `RUN` commands can be merged, no?

2020-04-29 23:44 UTC, sideeffffect commented
@ericwill
I've added the entrypoint.sh, hopefully now is everything correct

2020-05-05 10:13 UTC, sideeffffect commented
Hi @ericwill , have you had a change to look at this PR since I've amended it? :slightly_smiling_face:

2020-05-05 12:04 UTC, ericwill commented
Hi sorry for the delay. I'll take a look later today and get back to you.

2020-05-05 17:37 UTC, ericwill commented on .github/workflows/build-publish.yaml
> +      - '1.8.6'
This branch has to match the branch in GitHub. It's no big deal -- I'll create a 1.8.6 branch and you can propose a PR against that one.

2020-05-05 17:38 UTC, ericwill commented
I've created a new branch [1.8.6](https://github.com/che-dockerfiles/che-sidecar-scala/tree/1.8.6), please propose a new PR against that branch. Other than it LGTM.

2020-05-05 17:38 UTC, closed without merging